# Generated by Django 5.0.2 on 2024-02-17 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core_post.comment'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
