# Generated by Django 5.0.2 on 2024-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_comment_parent_comment_alter_userpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
