# Generated by Django 5.0.2 on 2024-03-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_topics_userpost_is_allow_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
