# Generated by Django 5.0.2 on 2024-03-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0003_userpost_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='allow_comments',
        ),
        migrations.AddField(
            model_name='userpost',
            name='show_to_close_friends',
            field=models.BooleanField(default=False),
        ),
    ]
