# Generated by Django 5.0.2 on 2024-03-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_auth_method',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Whatsapp SMS', 'Whatsapp SMS')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not confirmed', 'Not confirmed')], db_index=True, max_length=100, null=True),
        ),
    ]
