# Generated by Django 5.0.2 on 2024-03-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0002_user_two_factor_auth_method_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(db_index=True, default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Interest',
            field=models.ManyToManyField(blank=True, to='core_account.interest'),
        ),
    ]
