# Generated by Django 5.0.2 on 2024-02-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0002_postimagemedia_postvideomedia_userpost_comment_save_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='post',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='images',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='videos',
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='save',
            name='post',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='PostImageMedia',
        ),
        migrations.DeleteModel(
            name='PostVideoMedia',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
