# Generated by Django 5.0.2 on 2024-02-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0003_alter_favorite_unique_together_remove_favorite_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
