# Generated by Django 5.0.2 on 2024-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0005_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
